version: '3'
services:

  database:
    image: postgres:11.5-alpine
    container_name: database
    ports:
      - 5432:5432
    environment:
      - ALLOW_IP_RANGE='0.0.0.0/0'
      - POSTGRES_DB=database
      - POSTGRES_USER=database
      - POSTGRES_PASSWORD=password

  jaeger:
    image: jaegertracing/all-in-one:1.14
    container_name: jaeger
    ports:
      - 5778:5778
      - 9411:9411
      - 16686:16686
      - 14268:14268
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
