global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'number-api'
    static_configs:
      - targets: ['number-api:8081']
  - job_name: 'book-api'
    static_configs:
      - targets: ['book-api:8080']
