global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
- job_name: number-api
  scrape_interval: 5s
  metrics_path: '/number-api/metrics/'
  static_configs:
  - targets: ['number-api:8081']
- job_name: book-api
  scrape_interval: 5s
  metrics_path: '/book-api/metrics/'
  static_configs:
  - targets: ['book-api:8080']
- job_name: simulator
  scrape_interval: 5s
  metrics_path: '/simulator/metrics/'
  static_configs:
  - targets: ['simulator:9080']
