---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  labels:
    app: database
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:11.5-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: database
      restartPolicy: Always
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database
  labels:
    app: database
data:
  POSTGRES_DB: database
  POSTGRES_USER: database
  POSTGRES_PASSWORD: password
