---
- hosts: grom
  gather_facts: no
  remote_user: pirate
  become: yes
  become_method: sudo

  tasks:
  - name: Deploy Simulator
    docker_container:
      name: simulator
      image: docker-registry:5000/microprofile/mp-samples/simulator:rpi
      state: started
      restart: yes
      pull: true
      ports:
        - "9080:9080"
      env:
        CATALINA_OPTS: >-
          -Dcom.microprofile.samples.clients.simulator.BookService/mp-rest/url=http://pi-grom-database:8080/
          -Dcom.microprofile.samples.clients.simulator.TokenStoreClient/mp-rest/url=http://pi-grom-database:8080/
    when: (inventory_hostname == "pi-grom-load-balancer")
