---
- hosts: grom
  gather_facts: no
  remote_user: pirate
  become: yes
  become_method: sudo

  tasks:
  - name: Deploy Simulator
    docker_container:
      name: simulator
      image: docker-repo:5000/microprofile/mp-samples/simulator:rpi
      state: started
      restart: yes
      pull: true
      ports:
        - "9080:9080"
      env:
        CATALINA_OPTS: >-
          -Dcom.microprofile.samples.clients.simulator.BookService/mp-rest/url=http://pi-grom-database:8080/book-api
          -Dgeronimo.opentracing.zipkin.serviceName=simulator
          -Dgeronimo.opentracing.span.converter.zipkin.sender=http
          -Dgeronimo.opentracing.span.converter.zipkin.http.collector=http://docker-repo:9411/api/v2/spans
          -Dgeronimo.opentracing.span.converter.zipkin.http.bulkSendInterval=5000
          -Dgeronimo.opentracing.span.converter.zipkin.http.useV2=true
          -Dgeronimo.metrics.jaxrs.acceptedHosts=localhost,pi-grom-load-balancer,pi-grom-server-01,pi-grom-server-01,pi-grom-database
    when: (inventory_hostname == "pi-grom-load-balancer")
