---
- hosts: all
  gather_facts: no
  remote_user: pirate
  become: yes
  become_method: sudo

  tasks:
  - name: Copy configuration for Insecure Registry
    copy:
      src: daemon.json
      dest: "/etc/docker/daemon.json"
